### PR TITLE
Fixes for #169 added

### PR DESCRIPTION
**Pull request by p5k369**
- changed comparison values for display_name to str in function visual_whitepoint_editor_handler
- added uncritical integer conversion wherever needed in module wxVisualWhitepointEditor

### CODE REVIEW

**Comment by ledoge** [comment]
Thanks, it opens and works fine now. However, the layout is still a bit broken (specifically the square that you're supposed to put the colorimeter on).

This is what the window looks like with the PR:



And this is what it should look like (screenshot from the 3.8.9.3 release on Windows):

DisplayCAL_mxZ3orpUb9

**Comment by p5k369** [comment]
You're right, I overlooked one place which does not throw an error if an argument is float instead of an integer.

**Comment by ledoge** [comment]
Thanks, works great now!

**Comment by eoyilmaz** [comment]
Thank you Patrick :+1:

**Pull request merged**
