### PR TITLE
367 compiled sucessfully in w10 py311 but createprocess fails call to dispread to measure

### PR DESCRIPTION
**Pull request by eoyilmaz**
DisplayCAL now runs properly on Windows with Python 3.9, 3.10 and 3.11.

### CODE REVIEW

**Comment by AstralStorm** [comment]
Ok, it needs pythonw to launch processes or it fails to attach a TTY and hangs, and I actually get a nice isatty NoneType AttributeError on Windows. Will attempt to fix it.

**Comment by AstralStorm** [comment]
Ok, so it appears that frozen version does something extra in its script to make wexpect work:

From wexpect.py - that's probably the secret sauce, it runs a subscript that does something to grab the console...
```python
        # If we are running 'frozen', expect python.exe in the same directory
        # as the packed executable.
        # py2exe: The python executable can be included via setup script by
        # adding it to 'data_files'
        commandLine = '"%s" %s "%s"' % (
            os.path.join(dirname, "python.exe")
            if getattr(sys, "frozen", False)
            else os.path.join(os.path.dirname(sys.executable), "python.exe"),
            " ".join(pyargs),
            "import sys; sys.path = %s + sys.path;"
            "args = %s; from DisplayCAL import wexpect;"
            # "args = %s; import wexpect;"
            "wexpect.ConsoleReader(wexpect.join_args(args), %i, %i, cp='%s', c=%s, r=%s, logdir=%r)"
            % (
                ("%r" % spath).replace('"', r"\""),
                ("%r" % args).replace('"', r"\""),
                pid,
                tid,
                self.codepage,
                self.columns,
                self.rows,
                logdir,
            ),
        )
```

**Comment by AstralStorm** [comment]
```
2024-06-18 13:04:14,535 Traceback (most recent call last):
  File "C:\Projects\displaycal_venv\Lib\site-packages\DisplayCAL\wexpect.py", line 2621, in __init__
    SetConsoleOutputCP(cp)
TypeError: SetConsoleOutputCP() argument 1 must be int, not str
```

And that's that. Not sure how you want to set it to utf-8 with this API.

**Comment by AstralStorm** [comment]
There's more, I have a patch cooking, though while it's working, I'm not sure it's fully correct and I need to clean it up.

Specifically new Python as launched by wexpect gets no standard handles (stdin/out/err), while the Argyll subprocess created from that is told to inherit the handles. Since there's no stdio, Argyll processes told to run interactively just terminate. I can tell it to have its new fresh stdio, and it seems to work. Console is inherited with all its setting as that's not a file handle and we don't tell it to CREATE_NEW_CONSOLE.
Plus there's yet another Unicode bug in WAIT_TEMPLATE which I fixed.

**Comment by AstralStorm** [comment]
See https://github.com/eoyilmaz/displaycal-py3/pull/383 for the additional fixes. This is on top of this branch.

**Comment by AstralStorm** [comment]
@nelsonlim You should try my branch, yes it includes this one. That is supposed to work, drop me a line if it does not.

**Comment by eoyilmaz** [comment]
@nelsonlim please report this in another ticket, I'm read to merge this one.

**Pull request merged**
