### PR TITLE
Fix error on parsing ICC profiles

### PR DESCRIPTION
**Pull request by ledoge**
Without this change, I get the error `'dict_values' object is not subscriptable` when parsing a certain ICC profile by X-Rite (which I believe I cannot share due to copyright).

### CODE REVIEW

**Comment by p5k369** [comment]
Hey @ledoge, does this work with all profiles where the condition `if "en" in self:` is False and  `elif len(self)` is True or this a special treatment of the profile you cannot share?

**Comment by ledoge** [comment]
I looked at the code again. Turns out the initial commit was only a partial (but required as part of python 2 -> 3) fix, as that branch was not supposed to be hit in the first place. I properly fixed the function now by converting it to using byte strings, and also fixed two somewhat related issues where byte strings were not being decoded when parsing profiles.

**Comment by p5k369** [comment]
Hey @ledoge I took a look at the git history and think youre right. Would you mind adding a test for the str method?

**Comment by eoyilmaz** [comment]
Ahh yes, thank you for the MR!

**Pull request merged**
