### PR TITLE
Checkerboard test added

### PR DESCRIPTION
**Pull request by p5k369**
Test for checkerboard added. However there are lots of debug messages written right into the code. Personally I would rather use a debugger than rely on debugging messages written into the code. 
What do you think?

### CODE REVIEW

**Comment by adbowers** [comment]
In my experience, having debug messages in the code are invaluable, but only if they are off by default and controlled by a flag.

**Comment by eoyilmaz** [comment]
Hey Patrick,

Thanks for the PR,

I really don't like to use debuggers, and debug messages suites me better. Sorry for that, but I think we should keep the debug messages. But, if you have a tutorial or something to read which will help me to better use debuggers with Python I would definitely want to look into that.

**Comment by p5k369** [comment]
Hey Erkan,
I just wanted to let you know, I saw them and left them in, for me its fine.
Somewhere, I think, I read that you use pycharm for programming, that is also the IDE I am using which comes with a very user friendly debugger, that I use most of the time when I'm programming.
You simply set a (or several) breakpoints (also during runtime) and run it. I mainly use it to determine if a piece of code has been reached, to inspect an object's structure at runtime, or to find out what the value of a variable is or how it's changing.

If you feel like looking at jetbrains' nice example, you won't need more than 10 minutes to get it. Promised.
https://www.jetbrains.com/help/pycharm/part-1-debugging-python-code.html

Hey @adbowers I think its better than having no help at all, so I agree somehow :) 
But I also think one of the biggest differences is that the output of a message is based on programmer defined logic and it can break or be compromised if something else changes in the code. Then you may not understand why you are getting that message. 
And on the other hand you can simply mark the line you want to reach (in pycharm you mark the line at which you pause, so this line is not executed until you tell the debugger to continue) and then explore the objects, it's not as if you would get less information. In fact you get more if you wish.

**Comment by eoyilmaz** [comment]
> In my experience, having debug messages in the code are invaluable, but only if they are off by default and controlled by a flag.

Ah sorry I missed your message, I definitely agree with you :+1:

**Comment by eoyilmaz** [comment]
> Hey Erkan, I just wanted to let you know, I saw them and left them in, for me its fine. Somewhere, I think, I read that you use pycharm for programming, that is also the IDE I am using which comes with a very user friendly debugger, that I use most of the time when I'm programming. You simply set a (or several) breakpoints (also during runtime) and run it. I mainly use it to determine if a piece of code has been reached, to inspect an object's structure at runtime, or to find out what the value of a variable is or how it's changing.
> 
> If you feel like looking at jetbrains' nice example, you won't need more than 10 minutes to get it. Promised. https://www.jetbrains.com/help/pycharm/part-1-debugging-python-code.html
> 
> Hey @adbowers I think its better than having no help at all, so I agree somehow :) But I also think one of the biggest differences is that the output of a message is based on programmer defined logic and it can break or be compromised if something else changes in the code. Then you may not understand why you are getting that message. And on the other hand you can simply mark the line you want to reach (in pycharm you mark the line at which you pause, so this line is not executed until you tell the debugger to continue) and then explore the objects, it's not as if you would get less information. In fact you get more if you wish.

Yeah, I tired using PyCharm's debugger years ago, but I always get confused, it is very hard for me to see the order of things getting executed, I generally like to add ``print`` statements with some index in it like ``print("code is here 1")`` and then ``print("code is here 2")`` etc. and then I can track what the code path is more easily, and because it is printed, I can investigate and kind of build a map in my mind much easier than looking in to the current state of the variables and stuff.

**Pull request merged**
