### PR TITLE
Fixes #171

### LINKED ISSUE #171: Parsing of settings is broken
Selecting an entry in the "Settings" dropdown at the top should set the values under the Calibration, Profiling, 3D LUT and Verification tabs accordingly. For example, selecting sRGB should set the tone curve to sRGB under Calibration. Instead, all fields just appear to be set to their default values.

I tracked this down to the code here: https://github.com/eoyilmaz/displaycal-py3/blob/main/DisplayCAL/display_cal.py#L17900 . `options_displaycal` contains strings, but the parser tries to compare them to byte strings, which is why none of the settings are actually applied.

### PR DESCRIPTION
**Pull request by p5k369**
- switched from byte-str to str
- setcgf does not set a list for "whitepoint.x" and "3dlut.whitepoint.x" anymore

### CODE REVIEW

**Comment by ledoge** [comment]
Thank you, I can confirm that the settings are applied properly to the Calibration tab now. Upon further testing, I noticed that the settings selection should affect the Profiling tab, the 3D LUT tab (including whether it is selectable), and the Verification tab as well.

**Comment by p5k369** [comment]
> Upon further testing, I noticed that the settings selection should affect the Profiling tab, the 3D LUT tab (including whether it is selectable), and the Verification tab as well.

So it doesnt do that for you?

**Comment by ledoge** [comment]
>So it doesnt do that for you?

Indeed, only the first two tabs seem be affected by the selection.

**Comment by p5k369** [comment]
Did you check out the pull request or did you alter the existing code on your machine?
I cannot confirm that by testing it by myself, see the example attached. (don't be irritated by the translation of the ui, that has nothing to do with it)
Bildschirmfoto vom 2022-09-12 01-49-01

**Comment by ledoge** [comment]
Checked out your PR and didn't do any further modifications. Interestingly, switching to one of the 3D LUT presets does not activate the 3D LUT tab, but restarting DisplayCAL while one of them is selected results in it being enabled until I switch to another preset (If it's always enabled for you, maybe you enabled the tab under Options?). But other than that, none of the settings seem to load. For reference, here's what they should look like with the preset you selected:

image
image
image

Actually, after doing a bit more testing, the 3D LUT tab *sometimes* gets enabled when switching to a MadVR preset and seems to consistently get enabled when switching to one of the Prisma or Resolve presets. Very strange.

**Comment by p5k369** [comment]
ok, I see, I misunderstood the problem. So it works as expected for the calibration tab but profiling, 3D lut and verification need to be checked. It is very likely that there is some sort of comparison issue like we already had with the calibration tab.

**Comment by eoyilmaz** [comment]
Thank you Patrick :+1:

**Comment by p5k369** [comment]
No problem Erkan. This pr only addresses part of the issue. The other tabs may also suffer from a comparison problem byte-str == str

**Pull request merged**
