### PR TITLE
polishing setup.py added editorconfig for code style

### PR DESCRIPTION
**Pull request by kamikaze**
I don't have lot of time right now to do full development on an unknown project but I can help with code style, optimization etc. Also I could try to help with changes that would allow new developers to start/do development easier.

### CODE REVIEW

**Comment by eoyilmaz** [comment]
Hey thanks for the PR, my repository seems to be ahead of yours can you work out the conflicts, thank you.

**Comment by kamikaze** [comment]
done. also I see you are populating issues, I could take some simple if u wish

**Comment by eoyilmaz** [comment]
Hey thank you. Would be very nice if you pick any one of the issues :+1:

**Comment by eoyilmaz** [comment]
#18  should be trivial. Just replacing it with ``OrderedDict`` is enough. But there are extra methods implemented to the DisplayCAL version of ``OrderedDict`` such as ``__delslice__``, ``__getslice__``, ``__setslice__``, ``index``, ``insert``, ``reverse``, ``sort``.

We either need to directly replace all those calls to those methods with something doing the same job, which I believe is hard without enough tests that are proving that the code is still doing what it needs to do, or we may derive from Python ``OrderedDict`` and keep those methods, thus removing 90% of the code that is already covered by the Python ``OrderedDict``.

```python
from collections import OrderedDict as OreredDictPy

class OrderedDict(OrderedDictPy):

    # and remove any common methods
```

**Pull request merged**
