### PR TITLE
pytest GitHub action added

### PR DESCRIPTION
**Pull request by p5k369**
added workflow for perfoming automated tests and providing coverage report as artifact after each push via GitHub actions

### CODE REVIEW

**Comment by eoyilmaz** [comment]
Hey thanks for the PR :+1: 
As you didn't touch to many source files, I'm not going to do a full review. Merging it, thank you!.

**Comment by p5k369** [comment]
Its a bit of a commit mess because I wasnt on linux and could not set up a vm, so it was a bit of try and error as you see.
I'm really looking forward to this project as there is no alternative on Linux and it's badly needed for image editing and I think it's a great idea to port it to Qt.

**Comment by eoyilmaz** [comment]
This is definitely on my list. But we need to be sure that the core functionality is in place and working without any problems. :+1:

**Comment by eoyilmaz** [comment]
Hey @p5k369, can you update the GitHub actions to include Python 3.9 and 3.10 (if possible). The current version with Python 3.8 is working quite nicely, so why not have the other Python versions :+1:

**Comment by p5k369** [comment]
Hey @eoyilmaz I think that would be a good idea. At the moment there is one limiting factor. If we would let the github runner build wxpython for each python version than this would take approximately 2 hours only for compiling that single package.
wxPython wheels are only provided for python3.8 and manylinux1 seems to be no option with wxpython.
We could provide pre compiled packages on our own.

by the way check out my latest pull request https://github.com/eoyilmaz/displaycal-py3/pull/35 .  For me it is ok if you dont want to merge it, but it gives hints why the github actions fail atm

**Comment by p5k369** [comment]
Hey @eoyilmaz, 
I created the wxpython 4.1.1 wheels for ubuntu-20.04 and Python 3.8, 3.9 and 3.10 and updated the test pipeline. #46

**Pull request merged**
