### PR TITLE
Cleanup: remove no-longer-referenced get_known_folder_path, UserDirs class

### PR DESCRIPTION
**Pull request by jayaddison**
While looking at a similar build failure to the one mentioned in #218, I noticed that the `UserDirs` class (XDG-related functionality) where a translation-retrieval exception occurred may be part of an unused section of code.

As far as I can tell, the `UserDirs` class is only referenced by the `get_known_folder_path` method, which is _imported_ -- but not invoked -- by [`worker.py`](https://github.com/eoyilmaz/displaycal-py3/blob/acc89e580074a9c9ade4586fc73b286f101a4341/DisplayCAL/worker.py).

I ran _most_ tests for this locally, although I had some difficulty getting some of the tests to run in a containerized environment (so I'm leaning on continuous integration a bit, here).

(note for maintainers: this changeset currently applies cleanly to the `develop` branch, if that's a better place to direct this change)

### CODE REVIEW

**Comment by jayaddison** [comment]
Hm, I guess continuous integration didn't run for this pull request.  See the downstream branch here for a demonstration of the test results before and after the change from 015753b1f61f4bf3f26902b49fc2ecfeb254c822 is applied: https://github.com/jayaddison/displaycal-py3/commits/develop

**Review by p5k369 — CHANGES_REQUESTED** [review]
Hey @jayaddison,
you are right. That function was used by the original author around 2017 and never since. I think it can be removed.
However, please do not _commit_ to the main branch and instead to the _develop_ branch.

**Comment by jayaddison** [comment]
Thank you, @p5k369 - merge branch updated.

**Review by p5k369 — APPROVED** [review]
Hey @jayaddison thank you for your pr

**Comment by jayaddison** [comment]
You're welcome!  Thank you for the merge.

**Pull request merged**
