### PR TITLE
updated testing environment to python 3.12

### PR DESCRIPTION
**Pull request by p5k369**
- added python 3.12 for testing
- updated github actions

### CODE REVIEW

**Review by eoyilmaz — APPROVED** [review]

**Comment by p5k369** [comment]
@eoyilmaz Damn. I should have marked it as not ready for merge. I build the wheels for wxpython-4.2.1 and python 3.12 and uploaded them.
But there is some problem with pytest. It has nothing to do with the tests. I think something goes wrong during import when calling pytest. Even if all tests are skipped calling python3 -b pytest will segfault, also locally. I assume it has something to do with RealDisplaySizeMM, but can't confirm that right now.

**Comment by p5k369** [comment]
I'm 95% sure it is because of some issue with the c-extension.

**Comment by p5k369** [comment]
I think I was wrong, seems like the segfault is bound to the import of wx into the test module.

**Comment by eoyilmaz** [comment]
> Damn. I should have marked it as not ready for merge.

Aah, sorry about that.

> I'm 95% sure it is because of some issue with the c-extension.

I started to think it is time to remove this c-extension. I'm going to go over it again, but as I understand it is only doing some mundane task there of finding what is the pixel equvelant of the given dimensions in mm, that is ultra unnecessary if you ask me.

**Pull request merged**
